apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodblog
  namespace: victoria-workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: vickymariam/my-food-app:vic
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m 
            memory: 512Mi 
          requests:
            cpu: 200m 
            memory: 256Mi