name: Build, Push, and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-food-app:vic

  deploy-to-aks:
    name: 'Deploy to AKS'
    runs-on: ubuntu

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Azure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y azure-cli

  
    - name: Azure Login
      uses: azure/login@v1

      with:
        creds: '{"clientId": "${{ secrets.ARM_CLIENT_ID }}", "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}", "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}", "tenantId": "${{ secrets.ARM_TENANT_ID }}" }'   

   
    - name: get aks credentials
      run: az aks get-credentials --resource-group aks_docker --name aks_cluster_demo
 
    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl     
      
    - name: Kubectl Apply - Namespace
      run: kubectl apply -f ./namespace.yaml

    - name: Kubectl Apply - Deployment
      run: kubectl apply -f deployment.yaml

    - name: Kubectl Apply - Service
      run: kubectl apply -f service.yaml

    - name: Check Deployments
      run: kubectl get deployments -n victoria-workspace

    - name: Check Pods
      run: kubectl get pods -n victoria-workspace

    - name: Check Services
      run: kubectl get services -n victoria-workspace
